FSHOnly: true
fhirVersion: 4.0.1
canonical: https://www.medizininformatik-initiative.de/fhir/ext/modul-biobank
# name: "KDS Biobanken"
status: active
dependencies:
  de.basisprofil.r4: 
    uri: https://ig.fhir.de/basisprofile-de/1.4.0/
    version: 1.4.0